services:
  nordic-web-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nordic-web-dashboard
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
